Repository Swess/RiskGame, pull requests merged in 2019-11, with the labels that each got.

#14 Attack() method (missing tests)
  src/Map/Map.cpp
  src/Map/Map.h
  src/MapLoader/MapLoader.cpp
  src/Player/Player.cpp
  src/Player/Player.h
  src/Terminal/Terminal.cpp
  src/Terminal/Terminal.h
  src/main.cpp
Labels: enhancement

#18 Player's Attack Tests
  src/Dice/Dice.cpp
  src/Dice/Dice.h
  src/GameEngine/GameEngine.cpp
  src/Map/Map.cpp
  src/Player/Player.cpp
  src/Player/Player.h
  src/Player/PlayerDriver.cpp
  src/Player/PlayerDriver.h
  src/Terminal/Terminal.cpp
  src/Terminal/Terminal.h
  src/main.cpp
Labels: enhancement

#16 Fix maploader
  src/GameEngine/GameEngine.cpp
  src/MapLoader/MapLoader.cpp
  src/main.cpp
Labels: good first issue

#19 reinforce + little reinforcement
  src/Cards/Cards.cpp
  src/Cards/Cards.h
  src/Cards/CardsDriver.cpp
  src/Map/Map.cpp
  src/Map/Map.h
  src/Player/Player.cpp
  src/Player/Player.h
  src/Player/PlayerDriver.cpp
  src/Player/PlayerDriver.h
  src/main.cpp
Labels: enhancement

#25 Comments on player strategy classes
  src/Player/PlayerStrategies.cpp
  src/Player/PlayerStrategies.h
Labels: documentation
